org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Add these in your local gradle.properties (untracked) for real runs.
SUPABASE_URL=https://svgyjfqpgleywjjnqpda.supabase.co
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2Z3lqZnFwZ2xleXdqam5xcGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1ODMyMDYsImV4cCI6MjA4ODE1OTIwNn0.7mqtrOZ-X1_P7_9-2TY-PfGGhcA_A7kAvvha-DfQ8ec
